#!/usr/bin/env python3

import collections
import graphlib
import os
import subprocess
import sys

owner = {}
mains = set()
for path in sys.argv[1:]:
    for sym in subprocess.check_output(['nm', '-gjU', path]).splitlines():
        owner[sym] = path
        if sym in [b'_main', b'main', b'__main_argc_argv']:
            mains.add(path)

deps = collections.defaultdict(set)
for path in sys.argv[1:]:
    for sym in subprocess.check_output(['nm', '-gju', path]).splitlines():
        if sym in owner:
            deps[path].add(owner[sym])

for path in graphlib.TopologicalSorter(deps).static_order():
    indirect = set()
    for dep in deps[path]:
        indirect.update(deps[dep])
    deps[path].update(indirect)

print('ninja_dyndep_version = 1')
for main in sorted(mains):
    print('build', os.path.splitext(main)[0] + ':', 'dyndep |', ' '.join(sorted(deps[main])))
